plugins {
    id "com.android.application"
}

android {
    namespace "com.persie.spotifymuter"
    compileSdk 37

    defaultConfig {
        applicationId "com.persie.spotifymuter"
        minSdk 26
        targetSdk 37
        versionCode 1
        versionName "0.1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
