package p204p;

import java.util.List;

/* JADX INFO: loaded from: classes2.dex */
public final class jaw0 implements pc5 {

    /* JADX INFO: renamed from: a */
    public static final jaw0 f110564a = new jaw0();

    /* JADX INFO: renamed from: b */
    public static final List f110565b = h6f.m46715L("android-media-session.restrict_playing_state_when_connect_car_is_active", "android-media-session.media3_enabled", "listening-activity.visibility_indicator_enabled", "android-perf-tracking.observability_platform_enabled", "android-perf-tracking.ads_fetch_oops_sampling_bps", "android-perf-tracking.jank_coordinator_enabled", "rc-observable-aa-test.observable_property", "rc-observable-aa-test.observable_property_mixed", "android-gen-alpha.use_kids_view_get_children", "android-feature-nowplaying-queue-bottom-sheet.enable_mft_plus_queue", "android-video.allow_showing_music_videos_setting", "apps-music-libs-eventsender.send_full_ess2", "apps-music-libs-eventsender.enable_rate_limiter", "apps-music-libs-eventsender.max_batch_size", "apps-music-libs-eventsender.max_batch_bytes", "apps-music-libs-eventsender.background_worker_send", "apps-music-libs-eventsender.background_worker_send_on_stop", "apps-music-libs-eventsender.send_events_on_bcd_event", "apps-music-libs-eventsender.rate_limiting_rule_1_time_unit_seconds", "apps-music-libs-eventsender.rate_limiting_rule_1_events_per_time_unit", "apps-music-libs-eventsender.rate_limiting_rule_2_time_unit_seconds", "apps-music-libs-eventsender.rate_limiting_rule_2_events_per_time_unit", "apps-music-libs-eventsender.rate_limiting_rule_3_time_unit_seconds", "apps-music-libs-eventsender.rate_limiting_rule_3_events_per_time_unit", "apps-music-libs-eventsender.event_sending_interval_seconds", "apps-music-libs-eventsender.heartbeat_interval", "apps-music-libs-eventsender.heartbeat_retry_interval", "apps-music-libs-eventsender.retry_db_operations", "android-feature-kidsmode.debug_is_in_kids_mode", "android-address.show_address_settings_item", "android-boombox-settings.crossfade_enabled", "android-gen-alpha-account-creation.parental_consent_flow_enabled", "android-gen-alpha-account-creation.parental_controls_transition_entry_point_enabled", "android-player-settings-automix.automix_enabled", "settings-quickaccess.show_quick_access_settings_in_settings", "android-shuffle-settings-algorithm.settings_item_visible", "apps-music-features-remoteconfiguration.button_color", "android-audiobook-playerlistener.should_refresh_capping_state_on_player_error", "android-cal-rollout-service.enable_cal", "android-cal-rollout-service.minimum_gearhead_version", "android-gen-alpha-blocking.is_allowlisting_management_enabled", "android-gen-alpha-blocking.is_managed_account_allowlisting_requests_page_enabled", "android-gen-alpha-blocking.is_my_allowlisting_requests_page_enabled", "android-genalpha-limitedexperienceindicator.enabled");
}
