package p204p;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* JADX INFO: loaded from: classes10.dex */
public final class lu7 {

    /* JADX INFO: renamed from: a */
    public static final lu7 f137018a;

    /* JADX INFO: renamed from: b */
    public static final lu7 f137019b;

    /* JADX INFO: renamed from: c */
    public static final lu7 f137020c;

    /* JADX INFO: renamed from: d */
    public static final lu7 f137021d;

    /* JADX INFO: renamed from: e */
    public static final /* synthetic */ lu7[] f137022e;

    static {
        lu7 lu7Var = new lu7("AutoGenerated", 0);
        f137018a = lu7Var;
        lu7 lu7Var2 = new lu7("CreatorProvided", 1);
        f137019b = lu7Var2;
        lu7 lu7Var3 = new lu7("CreatorProvidedAndStatic", 2);
        f137020c = lu7Var3;
        lu7 lu7Var4 = new lu7("Static", 3);
        f137021d = lu7Var4;
        f137022e = new lu7[]{lu7Var, lu7Var2, lu7Var3, lu7Var4};
    }

    public static lu7 valueOf(String str) {
        return (lu7) Enum.valueOf(lu7.class, str);
    }

    public static lu7[] values() {
        return (lu7[]) f137022e.clone();
    }
}
