package p204p;

import java.util.Set;

/* JADX INFO: loaded from: classes10.dex */
public abstract class u2c {

    /* JADX INFO: renamed from: a */
    public static final Set f226061a = bk5.m29624m1(new gn80[]{gn80.SHARE_FORMAT_ENTITY, gn80.SHARE_FORMAT_WATCH_FEED_ENTITY_SHARE, gn80.SHARE_FORMAT_PLAYLIST_WITH_TRACKS, gn80.SHARE_FORMAT_VTEC, gn80.SHARE_FORMAT_DAYLIST, gn80.SHARE_FORMAT_MESSAGING_ACTIONS, gn80.SHARE_FORMAT_YOUR_SOUND_CAPSULE, gn80.SHARE_FORMAT_LISTENING_STATS, gn80.SHARE_FORMAT_MUSIC_VIDEO, gn80.SHARE_FORMAT_IN_APP_MESSAGING, gn80.SHARE_FORMAT_PRO_PLAYLIST, gn80.SHARE_FORMAT_PRO_PLAYLIST_WITH_TRACKS, gn80.SHARE_FORMAT_AI_PLAYLIST, gn80.SHARE_FORMAT_FANDOM_COLLECTIBLES, gn80.SHARE_FORMAT_SONG_DNA, gn80.SHARE_FORMAT_PROMPTED_PLAYLIST_DEFAULT});

    /* JADX INFO: renamed from: b */
    public static final Set f226062b = bk5.m29624m1(new gn80[]{gn80.SHARE_FORMAT_TRANSCRIPT, gn80.SHARE_FORMAT_TIMESTAMP_TRANSCRIPT});
}
