package p204p;

import android.os.Parcel;
import android.os.Parcelable;

/* JADX INFO: loaded from: classes5.dex */
public final class wx51 implements Parcelable {
    public static final Parcelable.Creator<wx51> CREATOR = new nc51(27);

    /* JADX INFO: renamed from: a */
    public final String f255938a;

    /* JADX INFO: renamed from: b */
    public final String f255939b;

    /* JADX INFO: renamed from: c */
    public final boolean f255940c;

    /* JADX INFO: renamed from: d */
    public final int f255941d;

    public wx51(String str, String str2, boolean z, int i) {
        this.f255938a = str;
        this.f255939b = str2;
        this.f255940c = z;
        this.f255941d = i;
    }

    @Override // android.os.Parcelable
    public final int describeContents() {
        return 0;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof wx51)) {
            return false;
        }
        wx51 wx51Var = (wx51) obj;
        return wj50.m88271j(this.f255938a, wx51Var.f255938a) && wj50.m88271j(this.f255939b, wx51Var.f255939b) && this.f255940c == wx51Var.f255940c && this.f255941d == wx51Var.f255941d;
    }

    public final int hashCode() {
        return edb.m38547C(this.f255941d) + s571.m77245d(s571.m77243b(this.f255938a.hashCode() * 31, 31, this.f255939b), 31, this.f255940c);
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        String str;
        parcel.writeString(this.f255938a);
        parcel.writeString(this.f255939b);
        parcel.writeInt(this.f255940c ? 1 : 0);
        int i2 = this.f255941d;
        if (i2 == 1) {
            str = "None";
        } else {
            if (i2 != 2) {
                throw null;
            }
            str = "AutoGenerated";
        }
        parcel.writeString(str);
    }
}
