package p204p;

import android.os.Parcel;
import android.os.Parcelable;

/* JADX INFO: loaded from: classes10.dex */
public final class xrx0 implements jsx0 {
    public static final Parcelable.Creator<xrx0> CREATOR = new xxw0(25);

    /* JADX INFO: renamed from: a */
    public final int f265432a;

    public xrx0(int i) {
        this.f265432a = i;
    }

    @Override // android.os.Parcelable
    public final int describeContents() {
        return 0;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        return (obj instanceof xrx0) && this.f265432a == ((xrx0) obj).f265432a;
    }

    public final int hashCode() {
        return edb.m38547C(this.f265432a);
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        String str;
        int i2 = this.f265432a;
        if (i2 == 1) {
            str = "None";
        } else if (i2 == 2) {
            str = "AutoGenerated";
        } else if (i2 == 3) {
            str = "CreatorProvided";
        } else if (i2 == 4) {
            str = "CreatorProvidedAndStatic";
        } else {
            if (i2 != 5) {
                throw null;
            }
            str = "Static";
        }
        parcel.writeString(str);
    }
}
